apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-pool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application-pool
  template:
    metadata:
      labels:
        app: application-pool
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: application-pool
      containers:
      - name: nginx
        image: nginx:latest
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: application-pool
spec:
  selector:
    app: application-pool
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: application-pool-cpu-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: application-pool
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 25 